import { LanguageConfig } from "@/types/language";

export const LANGUAGES: LanguageConfig[] = [
  {
    code: "zh",
    bcp47: "zh-CN",
    nameInNative: "中文",
    nameInKorean: "중국어",
    nameInEnglish: "Chinese",
    countryCode: "CN",
    flagEmoji: "🇨🇳",
    dir: "ltr",
    geminiLangName: "Simplified Chinese",
    speechSupported: true,
  },
  {
    code: "en",
    bcp47: "en-US",
    nameInNative: "English",
    nameInKorean: "영어",
    nameInEnglish: "English",
    countryCode: "US",
    flagEmoji: "🇺🇸",
    dir: "ltr",
    geminiLangName: "English",
    speechSupported: true,
  },
  {
    code: "ja",
    bcp47: "ja-JP",
    nameInNative: "日本語",
    nameInKorean: "일본어",
    nameInEnglish: "Japanese",
    countryCode: "JP",
    flagEmoji: "🇯🇵",
    dir: "ltr",
    geminiLangName: "Japanese",
    speechSupported: true,
  },
  {
    code: "ru",
    bcp47: "ru-RU",
    nameInNative: "Русский",
    nameInKorean: "러시아어",
    nameInEnglish: "Russian",
    countryCode: "RU",
    flagEmoji: "🇷🇺",
    dir: "ltr",
    geminiLangName: "Russian",
    speechSupported: true,
  },
  {
    code: "vi",
    bcp47: "vi-VN",
    nameInNative: "Tiếng Việt",
    nameInKorean: "베트남어",
    nameInEnglish: "Vietnamese",
    countryCode: "VN",
    flagEmoji: "🇻🇳",
    dir: "ltr",
    geminiLangName: "Vietnamese",
    speechSupported: true,
  },
  {
    code: "th",
    bcp47: "th-TH",
    nameInNative: "ภาษาไทย",
    nameInKorean: "태국어",
    nameInEnglish: "Thai",
    countryCode: "TH",
    flagEmoji: "🇹🇭",
    dir: "ltr",
    geminiLangName: "Thai",
    speechSupported: true,
  },
  {
    code: "mn",
    bcp47: "mn-MN",
    nameInNative: "Монгол",
    nameInKorean: "몽골어",
    nameInEnglish: "Mongolian",
    countryCode: "MN",
    flagEmoji: "🇲🇳",
    dir: "ltr",
    geminiLangName: "Mongolian",
    speechSupported: true,
  },
  {
    code: "tl",
    bcp47: "fil-PH",
    nameInNative: "Filipino",
    nameInKorean: "필리핀어",
    nameInEnglish: "Filipino",
    countryCode: "PH",
    flagEmoji: "🇵🇭",
    dir: "ltr",
    geminiLangName: "Filipino",
    speechSupported: true,
  },
  {
    code: "ar",
    bcp47: "ar-SA",
    nameInNative: "العربية",
    nameInKorean: "아랍어",
    nameInEnglish: "Arabic",
    countryCode: "SA",
    flagEmoji: "🇸🇦",
    dir: "rtl",
    geminiLangName: "Arabic",
    speechSupported: true,
  },
  {
    code: "uz",
    bcp47: "uz-UZ",
    nameInNative: "Oʻzbek",
    nameInKorean: "우즈베크어",
    nameInEnglish: "Uzbek",
    countryCode: "UZ",
    flagEmoji: "🇺🇿",
    dir: "ltr",
    geminiLangName: "Uzbek",
    speechSupported: true,
  },
  {
    code: "kk",
    bcp47: "kk-KZ",
    nameInNative: "Қазақ",
    nameInKorean: "카자흐어",
    nameInEnglish: "Kazakh",
    countryCode: "KZ",
    flagEmoji: "🇰🇿",
    dir: "ltr",
    geminiLangName: "Kazakh",
    speechSupported: true,
  },
  {
    code: "id",
    bcp47: "id-ID",
    nameInNative: "Bahasa Indonesia",
    nameInKorean: "인도네시아어",
    nameInEnglish: "Indonesian",
    countryCode: "ID",
    flagEmoji: "🇮🇩",
    dir: "ltr",
    geminiLangName: "Indonesian",
    speechSupported: true,
  },
  {
    code: "hi",
    bcp47: "hi-IN",
    nameInNative: "हिन्दी",
    nameInKorean: "힌디어",
    nameInEnglish: "Hindi",
    countryCode: "IN",
    flagEmoji: "🇮🇳",
    dir: "ltr",
    geminiLangName: "Hindi",
    speechSupported: true,
  },
  {
    code: "de",
    bcp47: "de-DE",
    nameInNative: "Deutsch",
    nameInKorean: "독일어",
    nameInEnglish: "German",
    countryCode: "DE",
    flagEmoji: "🇩🇪",
    dir: "ltr",
    geminiLangName: "German",
    speechSupported: true,
  },
  {
    code: "fr",
    bcp47: "fr-FR",
    nameInNative: "Français",
    nameInKorean: "프랑스어",
    nameInEnglish: "French",
    countryCode: "FR",
    flagEmoji: "🇫🇷",
    dir: "ltr",
    geminiLangName: "French",
    speechSupported: true,
  },
  {
    code: "my",
    bcp47: "my-MM",
    nameInNative: "မြန်မာ",
    nameInKorean: "미얀마어",
    nameInEnglish: "Burmese",
    countryCode: "MM",
    flagEmoji: "🇲🇲",
    dir: "ltr",
    geminiLangName: "Burmese",
    speechSupported: true,
  },
  {
    code: "km",
    bcp47: "km-KH",
    nameInNative: "ខ្មែរ",
    nameInKorean: "캄보디아어",
    nameInEnglish: "Khmer",
    countryCode: "KH",
    flagEmoji: "🇰🇭",
    dir: "ltr",
    geminiLangName: "Khmer",
    speechSupported: true,
  },
  {
    code: "ne",
    bcp47: "ne-NP",
    nameInNative: "नेपाली",
    nameInKorean: "네팔어",
    nameInEnglish: "Nepali",
    countryCode: "NP",
    flagEmoji: "🇳🇵",
    dir: "ltr",
    geminiLangName: "Nepali",
    speechSupported: true,
  },
  {
    code: "bn",
    bcp47: "bn-BD",
    nameInNative: "বাংলা",
    nameInKorean: "벵골어",
    nameInEnglish: "Bengali",
    countryCode: "BD",
    flagEmoji: "🇧🇩",
    dir: "ltr",
    geminiLangName: "Bengali",
    speechSupported: true,
  },
  {
    code: "es",
    bcp47: "es-ES",
    nameInNative: "Español",
    nameInKorean: "스페인어",
    nameInEnglish: "Spanish",
    countryCode: "ES",
    flagEmoji: "🇪🇸",
    dir: "ltr",
    geminiLangName: "Spanish",
    speechSupported: true,
  },
];

// Additional languages available via "Other" selection
export const EXTRA_LANGUAGES: LanguageConfig[] = [
  {
    code: "pt",
    bcp47: "pt-BR",
    nameInNative: "Português",
    nameInKorean: "포르투갈어",
    nameInEnglish: "Portuguese",
    countryCode: "BR",
    flagEmoji: "🇧🇷",
    dir: "ltr",
    geminiLangName: "Portuguese",
    speechSupported: true,
  },
  {
    code: "it",
    bcp47: "it-IT",
    nameInNative: "Italiano",
    nameInKorean: "이탈리아어",
    nameInEnglish: "Italian",
    countryCode: "IT",
    flagEmoji: "🇮🇹",
    dir: "ltr",
    geminiLangName: "Italian",
    speechSupported: true,
  },
  {
    code: "tr",
    bcp47: "tr-TR",
    nameInNative: "Türkçe",
    nameInKorean: "터키어",
    nameInEnglish: "Turkish",
    countryCode: "TR",
    flagEmoji: "🇹🇷",
    dir: "ltr",
    geminiLangName: "Turkish",
    speechSupported: true,
  },
  {
    code: "pl",
    bcp47: "pl-PL",
    nameInNative: "Polski",
    nameInKorean: "폴란드어",
    nameInEnglish: "Polish",
    countryCode: "PL",
    flagEmoji: "🇵🇱",
    dir: "ltr",
    geminiLangName: "Polish",
    speechSupported: true,
  },
  {
    code: "nl",
    bcp47: "nl-NL",
    nameInNative: "Nederlands",
    nameInKorean: "네덜란드어",
    nameInEnglish: "Dutch",
    countryCode: "NL",
    flagEmoji: "🇳🇱",
    dir: "ltr",
    geminiLangName: "Dutch",
    speechSupported: true,
  },
  {
    code: "sv",
    bcp47: "sv-SE",
    nameInNative: "Svenska",
    nameInKorean: "스웨덴어",
    nameInEnglish: "Swedish",
    countryCode: "SE",
    flagEmoji: "🇸🇪",
    dir: "ltr",
    geminiLangName: "Swedish",
    speechSupported: true,
  },
  {
    code: "uk",
    bcp47: "uk-UA",
    nameInNative: "Українська",
    nameInKorean: "우크라이나어",
    nameInEnglish: "Ukrainian",
    countryCode: "UA",
    flagEmoji: "🇺🇦",
    dir: "ltr",
    geminiLangName: "Ukrainian",
    speechSupported: true,
  },
  {
    code: "fa",
    bcp47: "fa-IR",
    nameInNative: "فارسی",
    nameInKorean: "페르시아어",
    nameInEnglish: "Persian",
    countryCode: "IR",
    flagEmoji: "🇮🇷",
    dir: "rtl",
    geminiLangName: "Persian",
    speechSupported: true,
  },
  {
    code: "he",
    bcp47: "he-IL",
    nameInNative: "עברית",
    nameInKorean: "히브리어",
    nameInEnglish: "Hebrew",
    countryCode: "IL",
    flagEmoji: "🇮🇱",
    dir: "rtl",
    geminiLangName: "Hebrew",
    speechSupported: true,
  },
  {
    code: "lo",
    bcp47: "lo-LA",
    nameInNative: "ລາວ",
    nameInKorean: "라오어",
    nameInEnglish: "Lao",
    countryCode: "LA",
    flagEmoji: "🇱🇦",
    dir: "ltr",
    geminiLangName: "Lao",
    speechSupported: true,
  },
  {
    code: "ms",
    bcp47: "ms-MY",
    nameInNative: "Bahasa Melayu",
    nameInKorean: "말레이어",
    nameInEnglish: "Malay",
    countryCode: "MY",
    flagEmoji: "🇲🇾",
    dir: "ltr",
    geminiLangName: "Malay",
    speechSupported: true,
  },
  {
    code: "sw",
    bcp47: "sw-KE",
    nameInNative: "Kiswahili",
    nameInKorean: "스와힐리어",
    nameInEnglish: "Swahili",
    countryCode: "KE",
    flagEmoji: "🇰🇪",
    dir: "ltr",
    geminiLangName: "Swahili",
    speechSupported: true,
  },
  {
    code: "ro",
    bcp47: "ro-RO",
    nameInNative: "Română",
    nameInKorean: "루마니아어",
    nameInEnglish: "Romanian",
    countryCode: "RO",
    flagEmoji: "🇷🇴",
    dir: "ltr",
    geminiLangName: "Romanian",
    speechSupported: true,
  },
  {
    code: "cs",
    bcp47: "cs-CZ",
    nameInNative: "Čeština",
    nameInKorean: "체코어",
    nameInEnglish: "Czech",
    countryCode: "CZ",
    flagEmoji: "🇨🇿",
    dir: "ltr",
    geminiLangName: "Czech",
    speechSupported: true,
  },
  {
    code: "hu",
    bcp47: "hu-HU",
    nameInNative: "Magyar",
    nameInKorean: "헝가리어",
    nameInEnglish: "Hungarian",
    countryCode: "HU",
    flagEmoji: "🇭🇺",
    dir: "ltr",
    geminiLangName: "Hungarian",
    speechSupported: true,
  },
  {
    code: "el",
    bcp47: "el-GR",
    nameInNative: "Ελληνικά",
    nameInKorean: "그리스어",
    nameInEnglish: "Greek",
    countryCode: "GR",
    flagEmoji: "🇬🇷",
    dir: "ltr",
    geminiLangName: "Greek",
    speechSupported: true,
  },
  {
    code: "ka",
    bcp47: "ka-GE",
    nameInNative: "ქართული",
    nameInKorean: "조지아어",
    nameInEnglish: "Georgian",
    countryCode: "GE",
    flagEmoji: "🇬🇪",
    dir: "ltr",
    geminiLangName: "Georgian",
    speechSupported: true,
  },
  {
    code: "am",
    bcp47: "am-ET",
    nameInNative: "አማርኛ",
    nameInKorean: "암하라어",
    nameInEnglish: "Amharic",
    countryCode: "ET",
    flagEmoji: "🇪🇹",
    dir: "ltr",
    geminiLangName: "Amharic",
    speechSupported: true,
  },
  {
    code: "ta",
    bcp47: "ta-IN",
    nameInNative: "தமிழ்",
    nameInKorean: "타밀어",
    nameInEnglish: "Tamil",
    countryCode: "IN",
    flagEmoji: "🇮🇳",
    dir: "ltr",
    geminiLangName: "Tamil",
    speechSupported: true,
  },
  {
    code: "ur",
    bcp47: "ur-PK",
    nameInNative: "اردو",
    nameInKorean: "우르두어",
    nameInEnglish: "Urdu",
    countryCode: "PK",
    flagEmoji: "🇵🇰",
    dir: "rtl",
    geminiLangName: "Urdu",
    speechSupported: true,
  },
];

export const ALL_LANGUAGES = [...LANGUAGES, ...EXTRA_LANGUAGES];

export function getLanguageByCode(code: string): LanguageConfig | undefined {
  return ALL_LANGUAGES.find((l) => l.code === code);
}

export const VALID_LANG_CODES = ALL_LANGUAGES.map((l) => l.code);
