import { LanguageConfig } from "@/types/language";

export const LANGUAGES: LanguageConfig[] = [
  {
    code: "zh",
    bcp47: "zh-CN",
    nameInNative: "中文",
    nameInKorean: "중국어",
    nameInEnglish: "Chinese",
    countryCode: "CN",
    flagEmoji: "🇨🇳",
    dir: "ltr",
    geminiLangName: "Simplified Chinese",
    speechSupported: true,
  },
  {
    code: "en",
    bcp47: "en-US",
    nameInNative: "English",
    nameInKorean: "영어",
    nameInEnglish: "English",
    countryCode: "US",
    flagEmoji: "🇺🇸",
    dir: "ltr",
    geminiLangName: "English",
    speechSupported: true,
  },
  {
    code: "ja",
    bcp47: "ja-JP",
    nameInNative: "日本語",
    nameInKorean: "일본어",
    nameInEnglish: "Japanese",
    countryCode: "JP",
    flagEmoji: "🇯🇵",
    dir: "ltr",
    geminiLangName: "Japanese",
    speechSupported: true,
  },
  {
    code: "ru",
    bcp47: "ru-RU",
    nameInNative: "Русский",
    nameInKorean: "러시아어",
    nameInEnglish: "Russian",
    countryCode: "RU",
    flagEmoji: "🇷🇺",
    dir: "ltr",
    geminiLangName: "Russian",
    speechSupported: true,
  },
  {
    code: "vi",
    bcp47: "vi-VN",
    nameInNative: "Tiếng Việt",
    nameInKorean: "베트남어",
    nameInEnglish: "Vietnamese",
    countryCode: "VN",
    flagEmoji: "🇻🇳",
    dir: "ltr",
    geminiLangName: "Vietnamese",
    speechSupported: true,
  },
  {
    code: "th",
    bcp47: "th-TH",
    nameInNative: "ภาษาไทย",
    nameInKorean: "태국어",
    nameInEnglish: "Thai",
    countryCode: "TH",
    flagEmoji: "🇹🇭",
    dir: "ltr",
    geminiLangName: "Thai",
    speechSupported: true,
  },
  {
    code: "mn",
    bcp47: "mn-MN",
    nameInNative: "Монгол",
    nameInKorean: "몽골어",
    nameInEnglish: "Mongolian",
    countryCode: "MN",
    flagEmoji: "🇲🇳",
    dir: "ltr",
    geminiLangName: "Mongolian",
    speechSupported: false,
  },
  {
    code: "tl",
    bcp47: "fil-PH",
    nameInNative: "Filipino",
    nameInKorean: "필리핀어",
    nameInEnglish: "Filipino",
    countryCode: "PH",
    flagEmoji: "🇵🇭",
    dir: "ltr",
    geminiLangName: "Filipino",
    speechSupported: true,
  },
  {
    code: "ar",
    bcp47: "ar-SA",
    nameInNative: "العربية",
    nameInKorean: "아랍어",
    nameInEnglish: "Arabic",
    countryCode: "SA",
    flagEmoji: "🇸🇦",
    dir: "rtl",
    geminiLangName: "Arabic",
    speechSupported: true,
  },
  {
    code: "uz",
    bcp47: "uz-UZ",
    nameInNative: "Oʻzbek",
    nameInKorean: "우즈베크어",
    nameInEnglish: "Uzbek",
    countryCode: "UZ",
    flagEmoji: "🇺🇿",
    dir: "ltr",
    geminiLangName: "Uzbek",
    speechSupported: false,
  },
  {
    code: "kk",
    bcp47: "kk-KZ",
    nameInNative: "Қазақ",
    nameInKorean: "카자흐어",
    nameInEnglish: "Kazakh",
    countryCode: "KZ",
    flagEmoji: "🇰🇿",
    dir: "ltr",
    geminiLangName: "Kazakh",
    speechSupported: false,
  },
  {
    code: "id",
    bcp47: "id-ID",
    nameInNative: "Bahasa Indonesia",
    nameInKorean: "인도네시아어",
    nameInEnglish: "Indonesian",
    countryCode: "ID",
    flagEmoji: "🇮🇩",
    dir: "ltr",
    geminiLangName: "Indonesian",
    speechSupported: true,
  },
  {
    code: "hi",
    bcp47: "hi-IN",
    nameInNative: "हिन्दी",
    nameInKorean: "힌디어",
    nameInEnglish: "Hindi",
    countryCode: "IN",
    flagEmoji: "🇮🇳",
    dir: "ltr",
    geminiLangName: "Hindi",
    speechSupported: true,
  },
  {
    code: "de",
    bcp47: "de-DE",
    nameInNative: "Deutsch",
    nameInKorean: "독일어",
    nameInEnglish: "German",
    countryCode: "DE",
    flagEmoji: "🇩🇪",
    dir: "ltr",
    geminiLangName: "German",
    speechSupported: true,
  },
  {
    code: "fr",
    bcp47: "fr-FR",
    nameInNative: "Français",
    nameInKorean: "프랑스어",
    nameInEnglish: "French",
    countryCode: "FR",
    flagEmoji: "🇫🇷",
    dir: "ltr",
    geminiLangName: "French",
    speechSupported: true,
  },
];

export function getLanguageByCode(code: string): LanguageConfig | undefined {
  return LANGUAGES.find((l) => l.code === code);
}

export const VALID_LANG_CODES = LANGUAGES.map((l) => l.code);
