export interface MedicalFieldLabels {
  chiefComplaint: string;
  pastMedicalHistory: string;
  surgicalHistory: string;
  currentMedications: string;
  otherInfo: string;
  chiefComplaintPlaceholder: string;
  pastMedicalHistoryPlaceholder: string;
  surgicalHistoryPlaceholder: string;
  currentMedicationsPlaceholder: string;
  otherInfoPlaceholder: string;
  nextButton: string;
  voiceInputHint: string;
  pageTitle: string;
  // Chat-style questionnaire labels
  chatGreeting: string;
  chiefComplaintQuestion: string;
  pastMedicalHistoryQuestion: string;
  surgicalHistoryQuestion: string;
  currentMedicationsQuestion: string;
  otherInfoQuestion: string;
  skipButton: string;
  sendButton: string;
  chatInputPlaceholder: string;
  thankYouMessage: string;
  completeButton: string;
  // Voice status messages
  listeningMessage: string;
  processingVoiceMessage: string;
  // Follow-up chat labels
  followUpGreeting: string;
  followUpCompleteMessage: string;
  followUpCompleteButton: string;
  followUpGenerating: string;
}

export const FIELD_KEYS = [
  "chiefComplaint",
  "pastMedicalHistory",
  "surgicalHistory",
  "currentMedications",
  "otherInfo",
] as const;

export type FieldKey = (typeof FIELD_KEYS)[number];

// Fallback: languages not in this map will use English labels
export function getMedicalLabels(langCode: string): MedicalFieldLabels {
  return MEDICAL_LABELS[langCode] || MEDICAL_LABELS.en;
}

export const MEDICAL_LABELS: Record<string, MedicalFieldLabels> = {
  zh: {
    pageTitle: "就诊前问卷",
    chiefComplaint: "主要症状",
    pastMedicalHistory: "既往病史",
    surgicalHistory: "手术史",
    currentMedications: "目前服用的药物",
    otherInfo: "其他特殊事项（过敏等）",
    chiefComplaintPlaceholder: "请描述您今天来就诊的原因",
    pastMedicalHistoryPlaceholder: "请列出您过去的疾病或健康状况",
    surgicalHistoryPlaceholder: "请列出您过去接受过的手术",
    currentMedicationsPlaceholder: "请列出您目前正在服用的药物",
    otherInfoPlaceholder: "请填写过敏、特殊情况等其他信息",
    nextButton: "下一步",
    voiceInputHint: "点击麦克风按钮可以使用语音输入",
    chatGreeting: "您好！我来帮您做就诊前问卷。请用文字或语音回答以下问题。",
    chiefComplaintQuestion: "请问您今天来就诊的主要原因或症状是什么？",
    pastMedicalHistoryQuestion: "请问您有什么既往病史吗？（如：高血压、糖尿病等）",
    surgicalHistoryQuestion: "请问您以前做过什么手术吗？",
    currentMedicationsQuestion: "请问您目前在服用什么药物吗？",
    otherInfoQuestion: "请问还有其他需要告知医生的信息吗？（如：过敏、怀孕等）",
    skipButton: "跳过",
    sendButton: "发送",
    chatInputPlaceholder: "请输入您的回答...",
    thankYouMessage: "感谢您的回答！问卷已完成。",
    completeButton: "完成问卷",
    listeningMessage: "🎤 正在聆听语音...(停止说话后自动发送)",
    processingVoiceMessage: "正在转换语音...",
    followUpGreeting: "现在我会根据您的症状提几个补充问题。请逐一回答。",
    followUpCompleteMessage: "感谢您的回答！补充问题已完成。",
    followUpCompleteButton: "查看摘要",
    followUpGenerating: "正在根据您的症状生成补充问题...",
  },
  en: {
    pageTitle: "Pre-Consultation Questionnaire",
    chiefComplaint: "Chief Complaint",
    pastMedicalHistory: "Past Medical History",
    surgicalHistory: "Surgical History",
    currentMedications: "Current Medications",
    otherInfo: "Other Notable Information (Allergies, etc.)",
    chiefComplaintPlaceholder: "Please describe the reason for your visit today",
    pastMedicalHistoryPlaceholder: "Please list your past illnesses or conditions",
    surgicalHistoryPlaceholder: "Please list any surgeries you have had",
    currentMedicationsPlaceholder: "Please list medications you are currently taking",
    otherInfoPlaceholder: "Please note any allergies, special conditions, etc.",
    nextButton: "Next",
    voiceInputHint: "Tap the microphone button to use voice input",
    chatGreeting: "Hello! I'll help you with the pre-consultation questionnaire. Please answer the following questions by text or voice.",
    chiefComplaintQuestion: "What is the main reason or symptom for your visit today?",
    pastMedicalHistoryQuestion: "Do you have any past medical history? (e.g., hypertension, diabetes, etc.)",
    surgicalHistoryQuestion: "Have you had any surgeries in the past?",
    currentMedicationsQuestion: "Are you currently taking any medications?",
    otherInfoQuestion: "Is there anything else the doctor should know? (e.g., allergies, pregnancy, etc.)",
    skipButton: "Skip",
    sendButton: "Send",
    chatInputPlaceholder: "Type your answer...",
    thankYouMessage: "Thank you for your answers! The questionnaire is complete.",
    completeButton: "Complete Questionnaire",
    listeningMessage: "🎤 Listening... (auto-sends when you stop speaking)",
    processingVoiceMessage: "Converting voice...",
    followUpGreeting: "Now I'll ask a few additional questions based on your symptoms. Please answer one at a time.",
    followUpCompleteMessage: "Thank you! All additional questions are complete.",
    followUpCompleteButton: "View Summary",
    followUpGenerating: "Generating additional questions based on your symptoms...",
  },
  ja: {
    pageTitle: "事前問診票",
    chiefComplaint: "主な症状",
    pastMedicalHistory: "既往歴",
    surgicalHistory: "手術歴",
    currentMedications: "現在服用中の薬",
    otherInfo: "その他の特記事項（アレルギーなど）",
    chiefComplaintPlaceholder: "本日の受診理由をお書きください",
    pastMedicalHistoryPlaceholder: "過去の病気や健康状態を記入してください",
    surgicalHistoryPlaceholder: "過去に受けた手術を記入してください",
    currentMedicationsPlaceholder: "現在服用中のお薬を記入してください",
    otherInfoPlaceholder: "アレルギーや特別な事情があれば記入してください",
    nextButton: "次へ",
    voiceInputHint: "マイクボタンをタップして音声入力できます",
    chatGreeting: "こんにちは！事前問診を行います。テキストまたは音声でお答えください。",
    chiefComplaintQuestion: "本日の受診理由や主な症状を教えてください。",
    pastMedicalHistoryQuestion: "これまでにかかった病気はありますか？（例：高血圧、糖尿病など）",
    surgicalHistoryQuestion: "これまでに手術を受けたことはありますか？",
    currentMedicationsQuestion: "現在服用中のお薬はありますか？",
    otherInfoQuestion: "他に医師に伝えたいことはありますか？（例：アレルギー、妊娠など）",
    skipButton: "スキップ",
    sendButton: "送信",
    chatInputPlaceholder: "回答を入力してください...",
    thankYouMessage: "ご回答ありがとうございます！問診は完了です。",
    completeButton: "問診を完了する",
    listeningMessage: "🎤 音声を聞いています...(話し終わると自動送信されます)",
    processingVoiceMessage: "音声を変換しています...",
    followUpGreeting: "症状に基づいていくつか追加の質問をさせていただきます。一つずつお答えください。",
    followUpCompleteMessage: "ありがとうございます！追加の質問は完了です。",
    followUpCompleteButton: "サマリーを見る",
    followUpGenerating: "症状に基づいて追加の質問を生成中...",
  },
  ru: {
    pageTitle: "Предварительная анкета",
    chiefComplaint: "Основные жалобы",
    pastMedicalHistory: "История болезни",
    surgicalHistory: "Хирургические операции",
    currentMedications: "Принимаемые лекарства",
    otherInfo: "Другая важная информация (аллергии и т.д.)",
    chiefComplaintPlaceholder: "Опишите причину вашего визита",
    pastMedicalHistoryPlaceholder: "Перечислите перенесённые заболевания",
    surgicalHistoryPlaceholder: "Перечислите перенесённые операции",
    currentMedicationsPlaceholder: "Перечислите принимаемые лекарства",
    otherInfoPlaceholder: "Укажите аллергии, особые состояния и т.д.",
    nextButton: "Далее",
    voiceInputHint: "Нажмите кнопку микрофона для голосового ввода",
    chatGreeting: "Здравствуйте! Я помогу вам заполнить предварительную анкету. Пожалуйста, отвечайте текстом или голосом.",
    chiefComplaintQuestion: "Какова основная причина или симптом вашего визита сегодня?",
    pastMedicalHistoryQuestion: "Есть ли у вас хронические заболевания? (например, гипертония, диабет и т.д.)",
    surgicalHistoryQuestion: "Были ли у вас операции в прошлом?",
    currentMedicationsQuestion: "Принимаете ли вы сейчас какие-либо лекарства?",
    otherInfoQuestion: "Есть ли ещё что-то, о чём должен знать врач? (аллергии, беременность и т.д.)",
    skipButton: "Пропустить",
    sendButton: "Отправить",
    chatInputPlaceholder: "Введите ваш ответ...",
    thankYouMessage: "Спасибо за ваши ответы! Анкета заполнена.",
    completeButton: "Завершить анкету",
    listeningMessage: "🎤 Слушаю... (автоматическая отправка после паузы)",
    processingVoiceMessage: "Преобразование голоса...",
    followUpGreeting: "Сейчас я задам несколько дополнительных вопросов на основе ваших симптомов. Пожалуйста, отвечайте по одному.",
    followUpCompleteMessage: "Спасибо! Все дополнительные вопросы заполнены.",
    followUpCompleteButton: "Посмотреть сводку",
    followUpGenerating: "Генерация дополнительных вопросов на основе ваших симптомов...",
  },
  vi: {
    pageTitle: "Phiếu khám bệnh sơ bộ",
    chiefComplaint: "Triệu chứng chính",
    pastMedicalHistory: "Tiền sử bệnh",
    surgicalHistory: "Tiền sử phẫu thuật",
    currentMedications: "Thuốc đang dùng",
    otherInfo: "Thông tin khác (dị ứng, v.v.)",
    chiefComplaintPlaceholder: "Vui lòng mô tả lý do khám bệnh hôm nay",
    pastMedicalHistoryPlaceholder: "Vui lòng liệt kê các bệnh đã mắc trước đây",
    surgicalHistoryPlaceholder: "Vui lòng liệt kê các phẫu thuật đã thực hiện",
    currentMedicationsPlaceholder: "Vui lòng liệt kê thuốc đang dùng",
    otherInfoPlaceholder: "Ghi chú dị ứng, tình trạng đặc biệt, v.v.",
    nextButton: "Tiếp theo",
    voiceInputHint: "Nhấn nút micro để nhập bằng giọng nói",
    chatGreeting: "Xin chào! Tôi sẽ giúp bạn điền phiếu khám bệnh sơ bộ. Vui lòng trả lời bằng văn bản hoặc giọng nói.",
    chiefComplaintQuestion: "Lý do chính hoặc triệu chứng khiến bạn đến khám hôm nay là gì?",
    pastMedicalHistoryQuestion: "Bạn có tiền sử bệnh nào không? (ví dụ: cao huyết áp, tiểu đường, v.v.)",
    surgicalHistoryQuestion: "Bạn đã từng phẫu thuật trước đây chưa?",
    currentMedicationsQuestion: "Bạn hiện đang dùng thuốc gì không?",
    otherInfoQuestion: "Có thông tin nào khác bác sĩ cần biết không? (ví dụ: dị ứng, mang thai, v.v.)",
    skipButton: "Bỏ qua",
    sendButton: "Gửi",
    chatInputPlaceholder: "Nhập câu trả lời của bạn...",
    thankYouMessage: "Cảm ơn bạn đã trả lời! Phiếu khám đã hoàn thành.",
    completeButton: "Hoàn thành phiếu khám",
    listeningMessage: "🎤 Đang nghe... (tự động gửi khi bạn ngừng nói)",
    processingVoiceMessage: "Đang chuyển đổi giọng nói...",
    followUpGreeting: "Bây giờ tôi sẽ hỏi thêm một vài câu hỏi dựa trên triệu chứng của bạn. Vui lòng trả lời từng câu.",
    followUpCompleteMessage: "Cảm ơn bạn! Tất cả câu hỏi bổ sung đã hoàn tất.",
    followUpCompleteButton: "Xem tóm tắt",
    followUpGenerating: "Đang tạo câu hỏi bổ sung dựa trên triệu chứng của bạn...",
  },
  th: {
    pageTitle: "แบบสอบถามก่อนตรวจ",
    chiefComplaint: "อาการสำคัญ",
    pastMedicalHistory: "ประวัติการเจ็บป่วย",
    surgicalHistory: "ประวัติการผ่าตัด",
    currentMedications: "ยาที่กำลังรับประทาน",
    otherInfo: "ข้อมูลอื่นๆ (การแพ้ยา ฯลฯ)",
    chiefComplaintPlaceholder: "กรุณาอธิบายอาการที่มาพบแพทย์วันนี้",
    pastMedicalHistoryPlaceholder: "กรุณาระบุโรคประจำตัวหรือโรคที่เคยเป็น",
    surgicalHistoryPlaceholder: "กรุณาระบุการผ่าตัดที่เคยทำ",
    currentMedicationsPlaceholder: "กรุณาระบุยาที่กำลังรับประทานอยู่",
    otherInfoPlaceholder: "กรุณาระบุการแพ้ยา สภาวะพิเศษ ฯลฯ",
    nextButton: "ถัดไป",
    voiceInputHint: "กดปุ่มไมโครโฟนเพื่อใช้การป้อนเสียง",
    chatGreeting: "สวัสดีค่ะ! ดิฉันจะช่วยคุณกรอกแบบสอบถามก่อนตรวจ กรุณาตอบด้วยข้อความหรือเสียง",
    chiefComplaintQuestion: "อาการสำคัญหรือสาเหตุที่มาพบแพทย์วันนี้คืออะไรคะ?",
    pastMedicalHistoryQuestion: "คุณมีประวัติการเจ็บป่วยใดบ้างคะ? (เช่น ความดันโลหิตสูง เบาหวาน ฯลฯ)",
    surgicalHistoryQuestion: "คุณเคยเข้ารับการผ่าตัดมาก่อนหรือไม่คะ?",
    currentMedicationsQuestion: "คุณกำลังรับประทานยาอะไรอยู่ในขณะนี้คะ?",
    otherInfoQuestion: "มีข้อมูลอื่นๆ ที่แพทย์ควรทราบไหมคะ? (เช่น การแพ้ยา การตั้งครรภ์ ฯลฯ)",
    skipButton: "ข้าม",
    sendButton: "ส่ง",
    chatInputPlaceholder: "พิมพ์คำตอบของคุณ...",
    thankYouMessage: "ขอบคุณสำหรับคำตอบค่ะ! แบบสอบถามเสร็จสมบูรณ์แล้ว",
    completeButton: "เสร็จสิ้นแบบสอบถาม",
    listeningMessage: "🎤 กำลังฟัง... (ส่งอัตโนมัติเมื่อคุณหยุดพูด)",
    processingVoiceMessage: "กำลังแปลงเสียง...",
    followUpGreeting: "ตอนนี้จะถามคำถามเพิ่มเติมตามอาการของคุณ กรุณาตอบทีละข้อค่ะ",
    followUpCompleteMessage: "ขอบคุณค่ะ! คำถามเพิ่มเติมเสร็จสมบูรณ์แล้ว",
    followUpCompleteButton: "ดูสรุป",
    followUpGenerating: "กำลังสร้างคำถามเพิ่มเติมจากอาการของคุณ...",
  },
  mn: {
    pageTitle: "Урьдчилсан асуумж",
    chiefComplaint: "Гол шинж тэмдэг",
    pastMedicalHistory: "Өвчний түүх",
    surgicalHistory: "Мэс заслын түүх",
    currentMedications: "Одоо хэрэглэж буй эм",
    otherInfo: "Бусад мэдээлэл (харшил г.м.)",
    chiefComplaintPlaceholder: "Өнөөдөр эмчид хандсан шалтгаанаа бичнэ үү",
    pastMedicalHistoryPlaceholder: "Өмнө өвчилж байсан өвчнүүдээ бичнэ үү",
    surgicalHistoryPlaceholder: "Өмнө хийлгэсэн мэс заслуудаа бичнэ үү",
    currentMedicationsPlaceholder: "Одоо хэрэглэж буй эмүүдээ бичнэ үү",
    otherInfoPlaceholder: "Харшил, онцгой нөхцөл байдлаа бичнэ үү",
    nextButton: "Дараах",
    voiceInputHint: "Текстээр оруулна уу (дуут оруулга боломжгүй)",
    chatGreeting: "Сайн байна уу! Урьдчилсан асуумж бөглөхөд туслах болно. Текстээр эсвэл дуугаар хариулна уу.",
    chiefComplaintQuestion: "Өнөөдөр эмчид хандсан гол шалтгаан юу вэ?",
    pastMedicalHistoryQuestion: "Өмнө ямар нэг өвчин тусаж байсан уу? (жнь: даралт ихсэх, чихрийн шижин г.м.)",
    surgicalHistoryQuestion: "Өмнө мэс засал хийлгэж байсан уу?",
    currentMedicationsQuestion: "Одоо ямар нэг эм хэрэглэж байна уу?",
    otherInfoQuestion: "Эмчид мэдэгдэх бусад зүйл бий юу? (жнь: харшил, жирэмслэлт г.м.)",
    skipButton: "Алгасах",
    sendButton: "Илгээх",
    chatInputPlaceholder: "Хариултаа бичнэ үү...",
    thankYouMessage: "Хариулт өгсөнд баярлалаа! Асуумж дууслаа.",
    completeButton: "Асуумж дуусгах",
    listeningMessage: "🎤 Сонсож байна... (ярьж дуусахад автоматаар илгээнэ)",
    processingVoiceMessage: "Дуу хөрвүүлж байна...",
    followUpGreeting: "Одоо таны шинж тэмдэгт үндэслэн нэмэлт асуулт асууна. Нэг нэгээр нь хариулна уу.",
    followUpCompleteMessage: "Баярлалаа! Нэмэлт асуултууд дууслаа.",
    followUpCompleteButton: "Хураангуй харах",
    followUpGenerating: "Таны шинж тэмдэгт үндэслэн нэмэлт асуулт үүсгэж байна...",
  },
  tl: {
    pageTitle: "Paunang Palatanungan",
    chiefComplaint: "Pangunahing Sintomas",
    pastMedicalHistory: "Nakaraang Kasaysayang Medikal",
    surgicalHistory: "Kasaysayan ng Operasyon",
    currentMedications: "Kasalukuyang Iniinom na Gamot",
    otherInfo: "Iba pang Impormasyon (Allergy, atbp.)",
    chiefComplaintPlaceholder: "Ilarawan ang dahilan ng iyong pagbisita ngayon",
    pastMedicalHistoryPlaceholder: "Ilista ang mga nakaraang sakit o kondisyon",
    surgicalHistoryPlaceholder: "Ilista ang mga nakaraang operasyon",
    currentMedicationsPlaceholder: "Ilista ang mga gamot na kasalukuyang iniinom",
    otherInfoPlaceholder: "Isulat ang mga allergy, espesyal na kondisyon, atbp.",
    nextButton: "Susunod",
    voiceInputHint: "Pindutin ang mikropono para sa voice input",
    chatGreeting: "Kumusta! Tutulungan ko kayong sagutan ang paunang palatanungan. Sumagot gamit ang text o boses.",
    chiefComplaintQuestion: "Ano ang pangunahing dahilan o sintomas ng iyong pagbisita ngayon?",
    pastMedicalHistoryQuestion: "Mayroon ka bang nakaraang sakit? (hal. high blood, diabetes, atbp.)",
    surgicalHistoryQuestion: "Nagkaroon ka na ba ng operasyon dati?",
    currentMedicationsQuestion: "May iniinom ka bang gamot ngayon?",
    otherInfoQuestion: "May iba pa bang dapat malaman ng doktor? (hal. allergy, pagbubuntis, atbp.)",
    skipButton: "Laktawan",
    sendButton: "Ipadala",
    chatInputPlaceholder: "I-type ang iyong sagot...",
    thankYouMessage: "Salamat sa iyong mga sagot! Kumpleto na ang palatanungan.",
    completeButton: "Kumpletuhin ang Palatanungan",
    listeningMessage: "🎤 Nakikinig... (awtomatikong ipapadala kapag tumigil ka sa pagsasalita)",
    processingVoiceMessage: "Kino-convert ang boses...",
    followUpGreeting: "Magtatanong ako ng ilang karagdagang tanong batay sa iyong mga sintomas. Sagutin mo isa-isa.",
    followUpCompleteMessage: "Salamat! Lahat ng karagdagang tanong ay nakumpleto na.",
    followUpCompleteButton: "Tingnan ang Buod",
    followUpGenerating: "Gumagawa ng karagdagang tanong batay sa iyong mga sintomas...",
  },
  ar: {
    pageTitle: "استبيان ما قبل الاستشارة",
    chiefComplaint: "الشكوى الرئيسية",
    pastMedicalHistory: "التاريخ المرضي",
    surgicalHistory: "التاريخ الجراحي",
    currentMedications: "الأدوية الحالية",
    otherInfo: "معلومات أخرى (حساسية، إلخ)",
    chiefComplaintPlaceholder: "يرجى وصف سبب زيارتك اليوم",
    pastMedicalHistoryPlaceholder: "يرجى ذكر الأمراض أو الحالات السابقة",
    surgicalHistoryPlaceholder: "يرجى ذكر العمليات الجراحية السابقة",
    currentMedicationsPlaceholder: "يرجى ذكر الأدوية التي تتناولها حالياً",
    otherInfoPlaceholder: "يرجى ذكر الحساسية أو الحالات الخاصة",
    nextButton: "التالي",
    voiceInputHint: "اضغط على زر الميكروفون للإدخال الصوتي",
    chatGreeting: "مرحباً! سأساعدك في ملء استبيان ما قبل الاستشارة. يرجى الإجابة بالنص أو الصوت.",
    chiefComplaintQuestion: "ما هو السبب الرئيسي أو العرض الذي جاء بك اليوم؟",
    pastMedicalHistoryQuestion: "هل لديك أي تاريخ مرضي سابق؟ (مثل: ارتفاع ضغط الدم، السكري، إلخ)",
    surgicalHistoryQuestion: "هل أجريت أي عمليات جراحية سابقاً؟",
    currentMedicationsQuestion: "هل تتناول أي أدوية حالياً؟",
    otherInfoQuestion: "هل هناك أي شيء آخر يجب أن يعرفه الطبيب؟ (مثل: حساسية، حمل، إلخ)",
    skipButton: "تخطي",
    sendButton: "إرسال",
    chatInputPlaceholder: "اكتب إجابتك...",
    thankYouMessage: "شكراً لإجاباتك! تم إكمال الاستبيان.",
    completeButton: "إكمال الاستبيان",
    listeningMessage: "🎤 جارٍ الاستماع... (سيتم الإرسال تلقائياً عند التوقف عن الكلام)",
    processingVoiceMessage: "جارٍ تحويل الصوت...",
    followUpGreeting: "الآن سأطرح بعض الأسئلة الإضافية بناءً على أعراضك. يرجى الإجابة واحداً تلو الآخر.",
    followUpCompleteMessage: "شكراً لك! تم إكمال جميع الأسئلة الإضافية.",
    followUpCompleteButton: "عرض الملخص",
    followUpGenerating: "جارٍ إنشاء أسئلة إضافية بناءً على أعراضك...",
  },
  uz: {
    pageTitle: "Dastlabki soʻrovnoma",
    chiefComplaint: "Asosiy shikoyat",
    pastMedicalHistory: "Kasallik tarixi",
    surgicalHistory: "Jarrohlik tarixi",
    currentMedications: "Hozirda qabul qilayotgan dorilar",
    otherInfo: "Boshqa maʼlumotlar (allergiya va h.k.)",
    chiefComplaintPlaceholder: "Bugungi tashrifingiz sababini tasvirlang",
    pastMedicalHistoryPlaceholder: "Oldingi kasalliklaringizni sanab oʻting",
    surgicalHistoryPlaceholder: "Oldingi jarrohlik amaliyotlaringizni sanab oʻting",
    currentMedicationsPlaceholder: "Hozirda qabul qilayotgan dorilaringizni sanab oʻting",
    otherInfoPlaceholder: "Allergiya, maxsus holatlar va h.k. haqida yozing",
    nextButton: "Keyingi",
    voiceInputHint: "Matn orqali kiriting (ovozli kiritish mavjud emas)",
    chatGreeting: "Salom! Dastlabki soʻrovnomani toʻldirishda yordam beraman. Matn yoki ovoz orqali javob bering.",
    chiefComplaintQuestion: "Bugungi tashrifingizning asosiy sababi yoki alomati nima?",
    pastMedicalHistoryQuestion: "Sizda oldingi kasalliklar bormi? (masalan: yuqori qon bosimi, diabet va h.k.)",
    surgicalHistoryQuestion: "Siz oldin jarrohlik amaliyot qildirganmisiz?",
    currentMedicationsQuestion: "Hozirda biror dori qabul qilyapsizmi?",
    otherInfoQuestion: "Shifokor bilishi kerak boʻlgan boshqa maʼlumot bormi? (masalan: allergiya, homiladorlik va h.k.)",
    skipButton: "Oʻtkazib yuborish",
    sendButton: "Yuborish",
    chatInputPlaceholder: "Javobingizni yozing...",
    thankYouMessage: "Javoblaringiz uchun rahmat! Soʻrovnoma yakunlandi.",
    completeButton: "Soʻrovnomani yakunlash",
    listeningMessage: "🎤 Tinglanmoqda... (gapirishni toʻxtatganingizda avtomatik yuboriladi)",
    processingVoiceMessage: "Ovoz aylantirilmoqda...",
    followUpGreeting: "Endi alomatlaringizga asosan bir nechta qoʻshimcha savol beraman. Birma-bir javob bering.",
    followUpCompleteMessage: "Rahmat! Barcha qoʻshimcha savollar yakunlandi.",
    followUpCompleteButton: "Xulosani koʻrish",
    followUpGenerating: "Alomatlaringizga asosan qoʻshimcha savollar yaratilmoqda...",
  },
  kk: {
    pageTitle: "Алдын ала сауалнама",
    chiefComplaint: "Негізгі шағым",
    pastMedicalHistory: "Ауру тарихы",
    surgicalHistory: "Хирургиялық тарих",
    currentMedications: "Қазір қабылдап жатқан дәрілер",
    otherInfo: "Басқа ақпарат (аллергия, т.б.)",
    chiefComplaintPlaceholder: "Бүгінгі келу себебіңізді сипаттаңыз",
    pastMedicalHistoryPlaceholder: "Бұрынғы ауруларыңызды жазыңыз",
    surgicalHistoryPlaceholder: "Бұрынғы операцияларыңызды жазыңыз",
    currentMedicationsPlaceholder: "Қазір қабылдап жатқан дәрілеріңізді жазыңыз",
    otherInfoPlaceholder: "Аллергия, ерекше жағдайларды жазыңыз",
    nextButton: "Келесі",
    voiceInputHint: "Мәтін арқылы енгізіңіз (дауыстық енгізу қол жетімді емес)",
    chatGreeting: "Сәлеметсіз бе! Алдын ала сауалнаманы толтыруға көмектесемін. Мәтін немесе дауыс арқылы жауап беріңіз.",
    chiefComplaintQuestion: "Бүгінгі келуіңіздің негізгі себебі немесе белгісі қандай?",
    pastMedicalHistoryQuestion: "Сізде бұрынғы аурулар бар ма? (мысалы: жоғары қан қысымы, қант диабеті, т.б.)",
    surgicalHistoryQuestion: "Бұрын операция жасатқансыз ба?",
    currentMedicationsQuestion: "Қазір қандай да бір дәрі қабылдайсыз ба?",
    otherInfoQuestion: "Дәрігер білуі тиіс тағы бір нәрсе бар ма? (мысалы: аллергия, жүктілік, т.б.)",
    skipButton: "Өткізіп жіберу",
    sendButton: "Жіберу",
    chatInputPlaceholder: "Жауабыңызды жазыңыз...",
    thankYouMessage: "Жауаптарыңызға рахмет! Сауалнама аяқталды.",
    completeButton: "Сауалнаманы аяқтау",
    listeningMessage: "🎤 Тыңдалуда... (сөйлеуді тоқтатқанда автоматты жіберіледі)",
    processingVoiceMessage: "Дауыс түрлендірілуде...",
    followUpGreeting: "Енді сіздің белгілеріңізге сүйене отырып бірнеше қосымша сұрақ қоямын. Бір-бірлеп жауап беріңіз.",
    followUpCompleteMessage: "Рахмет! Барлық қосымша сұрақтар аяқталды.",
    followUpCompleteButton: "Қорытындыны көру",
    followUpGenerating: "Белгілеріңізге сүйене отырып қосымша сұрақтар жасалуда...",
  },
  id: {
    pageTitle: "Kuesioner Pra-Konsultasi",
    chiefComplaint: "Keluhan Utama",
    pastMedicalHistory: "Riwayat Penyakit",
    surgicalHistory: "Riwayat Operasi",
    currentMedications: "Obat yang Sedang Dikonsumsi",
    otherInfo: "Informasi Lainnya (Alergi, dll.)",
    chiefComplaintPlaceholder: "Jelaskan alasan kunjungan Anda hari ini",
    pastMedicalHistoryPlaceholder: "Sebutkan penyakit atau kondisi yang pernah dialami",
    surgicalHistoryPlaceholder: "Sebutkan operasi yang pernah dilakukan",
    currentMedicationsPlaceholder: "Sebutkan obat yang sedang dikonsumsi",
    otherInfoPlaceholder: "Tuliskan alergi, kondisi khusus, dll.",
    nextButton: "Selanjutnya",
    voiceInputHint: "Tekan tombol mikrofon untuk input suara",
    chatGreeting: "Halo! Saya akan membantu Anda mengisi kuesioner pra-konsultasi. Silakan jawab dengan teks atau suara.",
    chiefComplaintQuestion: "Apa alasan utama atau gejala kunjungan Anda hari ini?",
    pastMedicalHistoryQuestion: "Apakah Anda memiliki riwayat penyakit? (misal: tekanan darah tinggi, diabetes, dll.)",
    surgicalHistoryQuestion: "Apakah Anda pernah menjalani operasi sebelumnya?",
    currentMedicationsQuestion: "Apakah Anda sedang mengonsumsi obat saat ini?",
    otherInfoQuestion: "Adakah hal lain yang perlu diketahui dokter? (misal: alergi, kehamilan, dll.)",
    skipButton: "Lewati",
    sendButton: "Kirim",
    chatInputPlaceholder: "Ketik jawaban Anda...",
    thankYouMessage: "Terima kasih atas jawaban Anda! Kuesioner telah selesai.",
    completeButton: "Selesaikan Kuesioner",
    listeningMessage: "🎤 Mendengarkan... (otomatis terkirim saat Anda berhenti bicara)",
    processingVoiceMessage: "Mengonversi suara...",
    followUpGreeting: "Sekarang saya akan bertanya beberapa pertanyaan tambahan berdasarkan gejala Anda. Silakan jawab satu per satu.",
    followUpCompleteMessage: "Terima kasih! Semua pertanyaan tambahan telah selesai.",
    followUpCompleteButton: "Lihat Ringkasan",
    followUpGenerating: "Membuat pertanyaan tambahan berdasarkan gejala Anda...",
  },
  hi: {
    pageTitle: "पूर्व-परामर्श प्रश्नावली",
    chiefComplaint: "मुख्य शिकायत",
    pastMedicalHistory: "पिछला चिकित्सा इतिहास",
    surgicalHistory: "सर्जरी का इतिहास",
    currentMedications: "वर्तमान में ली जा रही दवाइयाँ",
    otherInfo: "अन्य जानकारी (एलर्जी, आदि)",
    chiefComplaintPlaceholder: "आज की अपनी यात्रा का कारण बताएं",
    pastMedicalHistoryPlaceholder: "पिछली बीमारियों या स्थितियों की सूची दें",
    surgicalHistoryPlaceholder: "पिछली सर्जरी की सूची दें",
    currentMedicationsPlaceholder: "वर्तमान में ली जा रही दवाइयों की सूची दें",
    otherInfoPlaceholder: "एलर्जी, विशेष स्थिति आदि लिखें",
    nextButton: "अगला",
    voiceInputHint: "वॉयस इनपुट के लिए माइक्रोफ़ोन बटन दबाएं",
    chatGreeting: "नमस्ते! मैं आपको पूर्व-परामर्श प्रश्नावली भरने में मदद करूँगा। कृपया टेक्स्ट या आवाज़ से जवाब दें।",
    chiefComplaintQuestion: "आज आपकी यात्रा का मुख्य कारण या लक्षण क्या है?",
    pastMedicalHistoryQuestion: "क्या आपको पहले कोई बीमारी रही है? (जैसे: उच्च रक्तचाप, मधुमेह आदि)",
    surgicalHistoryQuestion: "क्या आपकी पहले कोई सर्जरी हुई है?",
    currentMedicationsQuestion: "क्या आप वर्तमान में कोई दवा ले रहे हैं?",
    otherInfoQuestion: "क्या कोई और बात है जो डॉक्टर को पता होनी चाहिए? (जैसे: एलर्जी, गर्भावस्था आदि)",
    skipButton: "छोड़ें",
    sendButton: "भेजें",
    chatInputPlaceholder: "अपना उत्तर लिखें...",
    thankYouMessage: "आपके उत्तरों के लिए धन्यवाद! प्रश्नावली पूर्ण हो गई।",
    completeButton: "प्रश्नावली पूर्ण करें",
    listeningMessage: "🎤 सुन रहे हैं... (बोलना बंद करने पर स्वचालित भेजा जाएगा)",
    processingVoiceMessage: "आवाज़ बदल रहे हैं...",
    followUpGreeting: "अब मैं आपके लक्षणों के आधार पर कुछ अतिरिक्त प्रश्न पूछूँगा। कृपया एक-एक करके उत्तर दें।",
    followUpCompleteMessage: "धन्यवाद! सभी अतिरिक्त प्रश्न पूरे हो गए।",
    followUpCompleteButton: "सारांश देखें",
    followUpGenerating: "आपके लक्षणों के आधार पर अतिरिक्त प्रश्न तैयार किए जा रहे हैं...",
  },
  de: {
    pageTitle: "Vorab-Fragebogen",
    chiefComplaint: "Hauptbeschwerde",
    pastMedicalHistory: "Krankengeschichte",
    surgicalHistory: "Operationsgeschichte",
    currentMedications: "Aktuelle Medikamente",
    otherInfo: "Weitere Informationen (Allergien usw.)",
    chiefComplaintPlaceholder: "Beschreiben Sie den Grund Ihres heutigen Besuchs",
    pastMedicalHistoryPlaceholder: "Listen Sie frühere Krankheiten oder Zustände auf",
    surgicalHistoryPlaceholder: "Listen Sie frühere Operationen auf",
    currentMedicationsPlaceholder: "Listen Sie Medikamente auf, die Sie derzeit einnehmen",
    otherInfoPlaceholder: "Geben Sie Allergien, besondere Umstände usw. an",
    nextButton: "Weiter",
    voiceInputHint: "Tippen Sie auf die Mikrofontaste für Spracheingabe",
    chatGreeting: "Hallo! Ich helfe Ihnen beim Ausfüllen des Vorab-Fragebogens. Bitte antworten Sie per Text oder Sprache.",
    chiefComplaintQuestion: "Was ist der Hauptgrund oder das Symptom für Ihren heutigen Besuch?",
    pastMedicalHistoryQuestion: "Haben Sie Vorerkrankungen? (z.B. Bluthochdruck, Diabetes usw.)",
    surgicalHistoryQuestion: "Hatten Sie in der Vergangenheit Operationen?",
    currentMedicationsQuestion: "Nehmen Sie derzeit Medikamente ein?",
    otherInfoQuestion: "Gibt es noch etwas, das der Arzt wissen sollte? (z.B. Allergien, Schwangerschaft usw.)",
    skipButton: "Überspringen",
    sendButton: "Senden",
    chatInputPlaceholder: "Geben Sie Ihre Antwort ein...",
    thankYouMessage: "Vielen Dank für Ihre Antworten! Der Fragebogen ist abgeschlossen.",
    completeButton: "Fragebogen abschließen",
    listeningMessage: "🎤 Zuhören... (wird automatisch gesendet, wenn Sie aufhören zu sprechen)",
    processingVoiceMessage: "Sprache wird konvertiert...",
    followUpGreeting: "Jetzt stelle ich Ihnen einige zusätzliche Fragen basierend auf Ihren Symptomen. Bitte antworten Sie nacheinander.",
    followUpCompleteMessage: "Vielen Dank! Alle zusätzlichen Fragen sind abgeschlossen.",
    followUpCompleteButton: "Zusammenfassung ansehen",
    followUpGenerating: "Zusätzliche Fragen werden basierend auf Ihren Symptomen erstellt...",
  },
  fr: {
    pageTitle: "Questionnaire de pré-consultation",
    chiefComplaint: "Motif principal de consultation",
    pastMedicalHistory: "Antécédents médicaux",
    surgicalHistory: "Antécédents chirurgicaux",
    currentMedications: "Médicaments actuels",
    otherInfo: "Autres informations (allergies, etc.)",
    chiefComplaintPlaceholder: "Décrivez la raison de votre visite aujourd'hui",
    pastMedicalHistoryPlaceholder: "Listez vos maladies ou conditions passées",
    surgicalHistoryPlaceholder: "Listez vos interventions chirurgicales passées",
    currentMedicationsPlaceholder: "Listez les médicaments que vous prenez actuellement",
    otherInfoPlaceholder: "Indiquez les allergies, conditions spéciales, etc.",
    nextButton: "Suivant",
    voiceInputHint: "Appuyez sur le bouton du microphone pour la saisie vocale",
    chatGreeting: "Bonjour ! Je vais vous aider à remplir le questionnaire de pré-consultation. Veuillez répondre par texte ou par voix.",
    chiefComplaintQuestion: "Quel est le motif principal ou le symptôme de votre visite aujourd'hui ?",
    pastMedicalHistoryQuestion: "Avez-vous des antécédents médicaux ? (ex : hypertension, diabète, etc.)",
    surgicalHistoryQuestion: "Avez-vous subi des interventions chirurgicales par le passé ?",
    currentMedicationsQuestion: "Prenez-vous actuellement des médicaments ?",
    otherInfoQuestion: "Y a-t-il autre chose que le médecin devrait savoir ? (ex : allergies, grossesse, etc.)",
    skipButton: "Passer",
    sendButton: "Envoyer",
    chatInputPlaceholder: "Tapez votre réponse...",
    thankYouMessage: "Merci pour vos réponses ! Le questionnaire est terminé.",
    completeButton: "Terminer le questionnaire",
    listeningMessage: "🎤 Écoute en cours... (envoi automatique quand vous arrêtez de parler)",
    processingVoiceMessage: "Conversion de la voix...",
    followUpGreeting: "Je vais maintenant vous poser quelques questions supplémentaires basées sur vos symptômes. Veuillez répondre une par une.",
    followUpCompleteMessage: "Merci ! Toutes les questions supplémentaires sont terminées.",
    followUpCompleteButton: "Voir le résumé",
    followUpGenerating: "Génération de questions supplémentaires basées sur vos symptômes...",
  },
  my: {
    pageTitle: "ကြိုတင်စစ်ဆေးမှု မေးခွန်းလွှာ",
    chiefComplaint: "အဓိက ရောဂါလက္ခဏာ",
    pastMedicalHistory: "ယခင် ဆေးကုသမှု မှတ်တမ်း",
    surgicalHistory: "ခွဲစိတ်ကုသမှု မှတ်တမ်း",
    currentMedications: "လက်ရှိ သောက်နေသော ဆေးများ",
    otherInfo: "အခြား အချက်အလက်များ (ဓာတ်မတည့်ခြင်း စသည်)",
    chiefComplaintPlaceholder: "ယနေ့ လာရောက်စစ်ဆေးရခြင်း အကြောင်းရင်းကို ဖော်ပြပါ",
    pastMedicalHistoryPlaceholder: "ယခင် ခံစားဖူးသော ရောဂါများကို ဖော်ပြပါ",
    surgicalHistoryPlaceholder: "ယခင် ခွဲစိတ်ကုသမှုများကို ဖော်ပြပါ",
    currentMedicationsPlaceholder: "လက်ရှိ သောက်နေသော ဆေးများကို ဖော်ပြပါ",
    otherInfoPlaceholder: "ဓာတ်မတည့်ခြင်း၊ အထူးအခြေအနေများကို ဖော်ပြပါ",
    nextButton: "ရှေ့ဆက်ရန်",
    voiceInputHint: "အသံဖြင့် ထည့်သွင်းရန် မိုက်ခရိုဖုန်း ခလုတ်ကို နှိပ်ပါ",
    chatGreeting: "မင်္ဂလာပါ! ကြိုတင်စစ်ဆေးမှု မေးခွန်းလွှာ ဖြည့်ရာတွင် ကူညီပေးပါမည်။ စာသားဖြင့် သို့မဟုတ် အသံဖြင့် ဖြေကြားပါ။",
    chiefComplaintQuestion: "ယနေ့ လာရောက်စစ်ဆေးရခြင်း၏ အဓိက အကြောင်းရင်း သို့မဟုတ် ရောဂါလက္ခဏာမှာ ဘာလဲ?",
    pastMedicalHistoryQuestion: "ယခင်က ရောဂါတစ်ခုခု ခံစားဖူးပါသလား? (ဥပမာ- သွေးတိုးရောဂါ၊ ဆီးချိုရောဂါ စသည်)",
    surgicalHistoryQuestion: "ယခင်က ခွဲစိတ်ကုသမှု ခံယူဖူးပါသလား?",
    currentMedicationsQuestion: "လက်ရှိ ဆေးတစ်ခုခု သောက်နေပါသလား?",
    otherInfoQuestion: "ဆရာဝန် သိထားသင့်သော အခြားအချက် ရှိပါသလား? (ဥပမာ- ဓာတ်မတည့်ခြင်း၊ ကိုယ်ဝန်ဆောင်ခြင်း စသည်)",
    skipButton: "ကျော်ရန်",
    sendButton: "ပို့ရန်",
    chatInputPlaceholder: "သင့်အဖြေကို ရိုက်ထည့်ပါ...",
    thankYouMessage: "ဖြေကြားပေးသည့်အတွက် ကျေးဇူးတင်ပါသည်! မေးခွန်းလွှာ ပြီးဆုံးပါပြီ။",
    completeButton: "မေးခွန်းလွှာ ပြီးဆုံးရန်",
    listeningMessage: "🎤 နားထောင်နေသည်... (စကားပြောရပ်လိုက်သောအခါ အလိုအလျောက် ပို့မည်)",
    processingVoiceMessage: "အသံ ပြောင်းနေသည်...",
    followUpGreeting: "ယခု သင့်ရောဂါလက္ခဏာအပေါ် အခြေခံ၍ နောက်ထပ် မေးခွန်းအချို့ မေးပါမည်။ တစ်ခုချင်းစီ ဖြေကြားပါ။",
    followUpCompleteMessage: "ကျေးဇူးတင်ပါသည်! နောက်ထပ် မေးခွန်းများ ပြီးဆုံးပါပြီ။",
    followUpCompleteButton: "အကျဉ်းချုပ် ကြည့်ရန်",
    followUpGenerating: "သင့်ရောဂါလက္ခဏာအပေါ် အခြေခံ၍ နောက်ထပ် မေးခွန်းများ ဖန်တီးနေသည်...",
  },
  km: {
    pageTitle: "កម្រងសំណួរមុនពេលពិគ្រោះ",
    chiefComplaint: "រោគសញ្ញាចម្បង",
    pastMedicalHistory: "ប្រវត្តិជំងឺ",
    surgicalHistory: "ប្រវត្តិវះកាត់",
    currentMedications: "ថ្នាំកំពុងប្រើ",
    otherInfo: "ព័ត៌មានផ្សេងទៀត (អាឡែស៊ី។ល។)",
    chiefComplaintPlaceholder: "សូមពិពណ៌នាមូលហេតុដែលមកពិនិត្យថ្ងៃនេះ",
    pastMedicalHistoryPlaceholder: "សូមរាយជំងឺឬស្ថានភាពសុខភាពពីមុន",
    surgicalHistoryPlaceholder: "សូមរាយការវះកាត់ដែលធ្លាប់ធ្វើ",
    currentMedicationsPlaceholder: "សូមរាយថ្នាំដែលកំពុងប្រើ",
    otherInfoPlaceholder: "សូមបញ្ជាក់អាឡែស៊ី ស្ថានភាពពិសេស។ល។",
    nextButton: "បន្ទាប់",
    voiceInputHint: "ចុចប៊ូតុងមីក្រូហ្វូនដើម្បីបញ្ចូលសំឡេង",
    chatGreeting: "សួស្តី! ខ្ញុំនឹងជួយអ្នកបំពេញកម្រងសំណួរមុនពេលពិគ្រោះ។ សូមឆ្លើយដោយអត្ថបទ ឬសំឡេង។",
    chiefComplaintQuestion: "មូលហេតុចម្បង ឬរោគសញ្ញាដែលអ្នកមកពិនិត្យថ្ងៃនេះគឺអ្វី?",
    pastMedicalHistoryQuestion: "តើអ្នកមានប្រវត្តិជំងឺអ្វីខ្លះ? (ឧ. លើសឈាម ទឹកនោមផ្អែម។ល។)",
    surgicalHistoryQuestion: "តើអ្នកធ្លាប់វះកាត់ពីមុនទេ?",
    currentMedicationsQuestion: "តើអ្នកកំពុងប្រើថ្នាំអ្វីខ្លះនាពេលបច្ចុប្បន្ន?",
    otherInfoQuestion: "តើមានព័ត៌មានផ្សេងទៀតដែលវេជ្ជបណ្ឌិតគួរដឹងទេ? (ឧ. អាឡែស៊ី ការមានផ្ទៃពោះ។ល។)",
    skipButton: "រំលង",
    sendButton: "ផ្ញើ",
    chatInputPlaceholder: "វាយចម្លើយរបស់អ្នក...",
    thankYouMessage: "សូមអរគុណសម្រាប់ចម្លើយរបស់អ្នក! កម្រងសំណួរបានបញ្ចប់។",
    completeButton: "បញ្ចប់កម្រងសំណួរ",
    listeningMessage: "🎤 កំពុងស្តាប់... (នឹងផ្ញើដោយស្វ័យប្រវត្តិនៅពេលអ្នកឈប់និយាយ)",
    processingVoiceMessage: "កំពុងបម្លែងសំឡេង...",
    followUpGreeting: "ឥឡូវខ្ញុំនឹងសួរសំណួរបន្ថែមដោយផ្អែកលើរោគសញ្ញារបស់អ្នក។ សូមឆ្លើយម្តងមួយ។",
    followUpCompleteMessage: "សូមអរគុណ! សំណួរបន្ថែមបានបញ្ចប់។",
    followUpCompleteButton: "មើលសេចក្តីសង្ខេប",
    followUpGenerating: "កំពុងបង្កើតសំណួរបន្ថែមដោយផ្អែកលើរោគសញ្ញារបស់អ្នក...",
  },
  ne: {
    pageTitle: "पूर्व-परामर्श प्रश्नावली",
    chiefComplaint: "मुख्य समस्या",
    pastMedicalHistory: "विगतको चिकित्सा इतिहास",
    surgicalHistory: "शल्यक्रिया इतिहास",
    currentMedications: "हाल खाइरहेका औषधिहरू",
    otherInfo: "अन्य जानकारी (एलर्जी, आदि)",
    chiefComplaintPlaceholder: "आज आउनुको कारण वर्णन गर्नुहोस्",
    pastMedicalHistoryPlaceholder: "पहिलेका रोग वा अवस्थाहरू लेख्नुहोस्",
    surgicalHistoryPlaceholder: "पहिलेका शल्यक्रियाहरू लेख्नुहोस्",
    currentMedicationsPlaceholder: "हाल खाइरहेका औषधिहरू लेख्नुहोस्",
    otherInfoPlaceholder: "एलर्जी, विशेष अवस्था आदि लेख्नुहोस्",
    nextButton: "अर्को",
    voiceInputHint: "आवाज इनपुटको लागि माइक्रोफोन बटन थिच्नुहोस्",
    chatGreeting: "नमस्ते! म तपाईंलाई पूर्व-परामर्श प्रश्नावली भर्न मद्दत गर्नेछु। कृपया टेक्स्ट वा आवाजद्वारा जवाफ दिनुहोस्।",
    chiefComplaintQuestion: "आज आउनुको मुख्य कारण वा लक्षण के हो?",
    pastMedicalHistoryQuestion: "तपाईंलाई पहिले कुनै रोग लागेको थियो? (जस्तै: उच्च रक्तचाप, मधुमेह आदि)",
    surgicalHistoryQuestion: "तपाईंको पहिले कुनै शल्यक्रिया भएको थियो?",
    currentMedicationsQuestion: "तपाईं हाल कुनै औषधि खाइरहनुभएको छ?",
    otherInfoQuestion: "डाक्टरलाई थाहा हुनुपर्ने अन्य कुरा छ? (जस्तै: एलर्जी, गर्भावस्था आदि)",
    skipButton: "छोड्नुहोस्",
    sendButton: "पठाउनुहोस्",
    chatInputPlaceholder: "आफ्नो जवाफ टाइप गर्नुहोस्...",
    thankYouMessage: "तपाईंको जवाफको लागि धन्यवाद! प्रश्नावली पूरा भयो।",
    completeButton: "प्रश्नावली पूरा गर्नुहोस्",
    listeningMessage: "🎤 सुनिरहेको छ... (बोल्न छाडेपछि स्वचालित पठाइनेछ)",
    processingVoiceMessage: "आवाज रूपान्तरण गर्दै...",
    followUpGreeting: "अब म तपाईंको लक्षणहरूको आधारमा केही थप प्रश्नहरू सोध्नेछु। कृपया एक-एक गरी जवाफ दिनुहोस्।",
    followUpCompleteMessage: "धन्यवाद! सबै थप प्रश्नहरू पूरा भए।",
    followUpCompleteButton: "सारांश हेर्नुहोस्",
    followUpGenerating: "तपाईंको लक्षणहरूको आधारमा थप प्रश्नहरू बनाइँदैछ...",
  },
  bn: {
    pageTitle: "পূর্ব-পরামর্শ প্রশ্নাবলী",
    chiefComplaint: "প্রধান সমস্যা",
    pastMedicalHistory: "পূর্ববর্তী চিকিৎসা ইতিহাস",
    surgicalHistory: "অস্ত্রোপচারের ইতিহাস",
    currentMedications: "বর্তমানে সেবনরত ওষুধ",
    otherInfo: "অন্যান্য তথ্য (অ্যালার্জি, ইত্যাদি)",
    chiefComplaintPlaceholder: "আজকের পরিদর্শনের কারণ বর্ণনা করুন",
    pastMedicalHistoryPlaceholder: "পূর্ববর্তী রোগ বা অবস্থাগুলি তালিকাভুক্ত করুন",
    surgicalHistoryPlaceholder: "পূর্ববর্তী অস্ত্রোপচারগুলি তালিকাভুক্ত করুন",
    currentMedicationsPlaceholder: "বর্তমানে সেবনরত ওষুধগুলি তালিকাভুক্ত করুন",
    otherInfoPlaceholder: "অ্যালার্জি, বিশেষ অবস্থা ইত্যাদি লিখুন",
    nextButton: "পরবর্তী",
    voiceInputHint: "ভয়েস ইনপুটের জন্য মাইক্রোফোন বোতাম টিপুন",
    chatGreeting: "নমস্কার! আমি আপনাকে পূর্ব-পরামর্শ প্রশ্নাবলী পূরণ করতে সাহায্য করব। অনুগ্রহ করে টেক্সট বা ভয়েসের মাধ্যমে উত্তর দিন।",
    chiefComplaintQuestion: "আজকের পরিদর্শনের প্রধান কারণ বা উপসর্গ কী?",
    pastMedicalHistoryQuestion: "আপনার কি পূর্ববর্তী কোনো রোগ আছে? (যেমন: উচ্চ রক্তচাপ, ডায়াবেটিস ইত্যাদি)",
    surgicalHistoryQuestion: "আপনার কি আগে কোনো অস্ত্রোপচার হয়েছে?",
    currentMedicationsQuestion: "আপনি কি বর্তমানে কোনো ওষুধ সেবন করছেন?",
    otherInfoQuestion: "ডাক্তারের জানা উচিত এমন আর কিছু আছে কি? (যেমন: অ্যালার্জি, গর্ভাবস্থা ইত্যাদি)",
    skipButton: "এড়িয়ে যান",
    sendButton: "পাঠান",
    chatInputPlaceholder: "আপনার উত্তর টাইপ করুন...",
    thankYouMessage: "আপনার উত্তরের জন্য ধন্যবাদ! প্রশ্নাবলী সম্পূর্ণ হয়েছে।",
    completeButton: "প্রশ্নাবলী সম্পূর্ণ করুন",
    listeningMessage: "🎤 শুনছি... (কথা বলা বন্ধ করলে স্বয়ংক্রিয়ভাবে পাঠানো হবে)",
    processingVoiceMessage: "ভয়েস রূপান্তর করা হচ্ছে...",
    followUpGreeting: "এখন আপনার উপসর্গের উপর ভিত্তি করে কিছু অতিরিক্ত প্রশ্ন জিজ্ঞেস করব। অনুগ্রহ করে একটি একটি করে উত্তর দিন।",
    followUpCompleteMessage: "ধন্যবাদ! সমস্ত অতিরিক্ত প্রশ্ন সম্পূর্ণ হয়েছে।",
    followUpCompleteButton: "সারসংক্ষেপ দেখুন",
    followUpGenerating: "আপনার উপসর্গের উপর ভিত্তি করে অতিরিক্ত প্রশ্ন তৈরি করা হচ্ছে...",
  },
  es: {
    pageTitle: "Cuestionario previo a la consulta",
    chiefComplaint: "Motivo principal de consulta",
    pastMedicalHistory: "Antecedentes médicos",
    surgicalHistory: "Antecedentes quirúrgicos",
    currentMedications: "Medicamentos actuales",
    otherInfo: "Otra información (alergias, etc.)",
    chiefComplaintPlaceholder: "Describa el motivo de su visita hoy",
    pastMedicalHistoryPlaceholder: "Enumere sus enfermedades o condiciones previas",
    surgicalHistoryPlaceholder: "Enumere sus cirugías previas",
    currentMedicationsPlaceholder: "Enumere los medicamentos que toma actualmente",
    otherInfoPlaceholder: "Indique alergias, condiciones especiales, etc.",
    nextButton: "Siguiente",
    voiceInputHint: "Pulse el botón del micrófono para entrada de voz",
    chatGreeting: "¡Hola! Le ayudaré a completar el cuestionario previo a la consulta. Por favor, responda con texto o voz.",
    chiefComplaintQuestion: "¿Cuál es el motivo principal o síntoma de su visita hoy?",
    pastMedicalHistoryQuestion: "¿Tiene antecedentes médicos? (ej. hipertensión, diabetes, etc.)",
    surgicalHistoryQuestion: "¿Ha tenido alguna cirugía anteriormente?",
    currentMedicationsQuestion: "¿Está tomando algún medicamento actualmente?",
    otherInfoQuestion: "¿Hay algo más que el médico deba saber? (ej. alergias, embarazo, etc.)",
    skipButton: "Omitir",
    sendButton: "Enviar",
    chatInputPlaceholder: "Escriba su respuesta...",
    thankYouMessage: "¡Gracias por sus respuestas! El cuestionario está completo.",
    completeButton: "Completar cuestionario",
    listeningMessage: "🎤 Escuchando... (se enviará automáticamente al dejar de hablar)",
    processingVoiceMessage: "Convirtiendo voz...",
    followUpGreeting: "Ahora le haré algunas preguntas adicionales basadas en sus síntomas. Por favor, responda una a una.",
    followUpCompleteMessage: "¡Gracias! Todas las preguntas adicionales están completas.",
    followUpCompleteButton: "Ver resumen",
    followUpGenerating: "Generando preguntas adicionales basadas en sus síntomas...",
  },
};
