export interface MedicalFieldLabels {
  chiefComplaint: string;
  pastMedicalHistory: string;
  surgicalHistory: string;
  currentMedications: string;
  otherInfo: string;
  chiefComplaintPlaceholder: string;
  pastMedicalHistoryPlaceholder: string;
  surgicalHistoryPlaceholder: string;
  currentMedicationsPlaceholder: string;
  otherInfoPlaceholder: string;
  nextButton: string;
  voiceInputHint: string;
  pageTitle: string;
}

export const FIELD_KEYS = [
  "chiefComplaint",
  "pastMedicalHistory",
  "surgicalHistory",
  "currentMedications",
  "otherInfo",
] as const;

export type FieldKey = (typeof FIELD_KEYS)[number];

export const MEDICAL_LABELS: Record<string, MedicalFieldLabels> = {
  zh: {
    pageTitle: "就诊前问卷",
    chiefComplaint: "主要症状",
    pastMedicalHistory: "既往病史",
    surgicalHistory: "手术史",
    currentMedications: "目前服用的药物",
    otherInfo: "其他特殊事项（过敏等）",
    chiefComplaintPlaceholder: "请描述您今天来就诊的原因",
    pastMedicalHistoryPlaceholder: "请列出您过去的疾病或健康状况",
    surgicalHistoryPlaceholder: "请列出您过去接受过的手术",
    currentMedicationsPlaceholder: "请列出您目前正在服用的药物",
    otherInfoPlaceholder: "请填写过敏、特殊情况等其他信息",
    nextButton: "下一步",
    voiceInputHint: "点击麦克风按钮可以使用语音输入",
  },
  en: {
    pageTitle: "Pre-Consultation Questionnaire",
    chiefComplaint: "Chief Complaint",
    pastMedicalHistory: "Past Medical History",
    surgicalHistory: "Surgical History",
    currentMedications: "Current Medications",
    otherInfo: "Other Notable Information (Allergies, etc.)",
    chiefComplaintPlaceholder: "Please describe the reason for your visit today",
    pastMedicalHistoryPlaceholder: "Please list your past illnesses or conditions",
    surgicalHistoryPlaceholder: "Please list any surgeries you have had",
    currentMedicationsPlaceholder: "Please list medications you are currently taking",
    otherInfoPlaceholder: "Please note any allergies, special conditions, etc.",
    nextButton: "Next",
    voiceInputHint: "Tap the microphone button to use voice input",
  },
  ja: {
    pageTitle: "事前問診票",
    chiefComplaint: "主な症状",
    pastMedicalHistory: "既往歴",
    surgicalHistory: "手術歴",
    currentMedications: "現在服用中の薬",
    otherInfo: "その他の特記事項（アレルギーなど）",
    chiefComplaintPlaceholder: "本日の受診理由をお書きください",
    pastMedicalHistoryPlaceholder: "過去の病気や健康状態を記入してください",
    surgicalHistoryPlaceholder: "過去に受けた手術を記入してください",
    currentMedicationsPlaceholder: "現在服用中のお薬を記入してください",
    otherInfoPlaceholder: "アレルギーや特別な事情があれば記入してください",
    nextButton: "次へ",
    voiceInputHint: "マイクボタンをタップして音声入力できます",
  },
  ru: {
    pageTitle: "Предварительная анкета",
    chiefComplaint: "Основные жалобы",
    pastMedicalHistory: "История болезни",
    surgicalHistory: "Хирургические операции",
    currentMedications: "Принимаемые лекарства",
    otherInfo: "Другая важная информация (аллергии и т.д.)",
    chiefComplaintPlaceholder: "Опишите причину вашего визита",
    pastMedicalHistoryPlaceholder: "Перечислите перенесённые заболевания",
    surgicalHistoryPlaceholder: "Перечислите перенесённые операции",
    currentMedicationsPlaceholder: "Перечислите принимаемые лекарства",
    otherInfoPlaceholder: "Укажите аллергии, особые состояния и т.д.",
    nextButton: "Далее",
    voiceInputHint: "Нажмите кнопку микрофона для голосового ввода",
  },
  vi: {
    pageTitle: "Phiếu khám bệnh sơ bộ",
    chiefComplaint: "Triệu chứng chính",
    pastMedicalHistory: "Tiền sử bệnh",
    surgicalHistory: "Tiền sử phẫu thuật",
    currentMedications: "Thuốc đang dùng",
    otherInfo: "Thông tin khác (dị ứng, v.v.)",
    chiefComplaintPlaceholder: "Vui lòng mô tả lý do khám bệnh hôm nay",
    pastMedicalHistoryPlaceholder: "Vui lòng liệt kê các bệnh đã mắc trước đây",
    surgicalHistoryPlaceholder: "Vui lòng liệt kê các phẫu thuật đã thực hiện",
    currentMedicationsPlaceholder: "Vui lòng liệt kê thuốc đang dùng",
    otherInfoPlaceholder: "Ghi chú dị ứng, tình trạng đặc biệt, v.v.",
    nextButton: "Tiếp theo",
    voiceInputHint: "Nhấn nút micro để nhập bằng giọng nói",
  },
  th: {
    pageTitle: "แบบสอบถามก่อนตรวจ",
    chiefComplaint: "อาการสำคัญ",
    pastMedicalHistory: "ประวัติการเจ็บป่วย",
    surgicalHistory: "ประวัติการผ่าตัด",
    currentMedications: "ยาที่กำลังรับประทาน",
    otherInfo: "ข้อมูลอื่นๆ (การแพ้ยา ฯลฯ)",
    chiefComplaintPlaceholder: "กรุณาอธิบายอาการที่มาพบแพทย์วันนี้",
    pastMedicalHistoryPlaceholder: "กรุณาระบุโรคประจำตัวหรือโรคที่เคยเป็น",
    surgicalHistoryPlaceholder: "กรุณาระบุการผ่าตัดที่เคยทำ",
    currentMedicationsPlaceholder: "กรุณาระบุยาที่กำลังรับประทานอยู่",
    otherInfoPlaceholder: "กรุณาระบุการแพ้ยา สภาวะพิเศษ ฯลฯ",
    nextButton: "ถัดไป",
    voiceInputHint: "กดปุ่มไมโครโฟนเพื่อใช้การป้อนเสียง",
  },
  mn: {
    pageTitle: "Урьдчилсан асуумж",
    chiefComplaint: "Гол шинж тэмдэг",
    pastMedicalHistory: "Өвчний түүх",
    surgicalHistory: "Мэс заслын түүх",
    currentMedications: "Одоо хэрэглэж буй эм",
    otherInfo: "Бусад мэдээлэл (харшил г.м.)",
    chiefComplaintPlaceholder: "Өнөөдөр эмчид хандсан шалтгаанаа бичнэ үү",
    pastMedicalHistoryPlaceholder: "Өмнө өвчилж байсан өвчнүүдээ бичнэ үү",
    surgicalHistoryPlaceholder: "Өмнө хийлгэсэн мэс заслуудаа бичнэ үү",
    currentMedicationsPlaceholder: "Одоо хэрэглэж буй эмүүдээ бичнэ үү",
    otherInfoPlaceholder: "Харшил, онцгой нөхцөл байдлаа бичнэ үү",
    nextButton: "Дараах",
    voiceInputHint: "Текстээр оруулна уу (дуут оруулга боломжгүй)",
  },
  tl: {
    pageTitle: "Paunang Palatanungan",
    chiefComplaint: "Pangunahing Sintomas",
    pastMedicalHistory: "Nakaraang Kasaysayang Medikal",
    surgicalHistory: "Kasaysayan ng Operasyon",
    currentMedications: "Kasalukuyang Iniinom na Gamot",
    otherInfo: "Iba pang Impormasyon (Allergy, atbp.)",
    chiefComplaintPlaceholder: "Ilarawan ang dahilan ng iyong pagbisita ngayon",
    pastMedicalHistoryPlaceholder: "Ilista ang mga nakaraang sakit o kondisyon",
    surgicalHistoryPlaceholder: "Ilista ang mga nakaraang operasyon",
    currentMedicationsPlaceholder: "Ilista ang mga gamot na kasalukuyang iniinom",
    otherInfoPlaceholder: "Isulat ang mga allergy, espesyal na kondisyon, atbp.",
    nextButton: "Susunod",
    voiceInputHint: "Pindutin ang mikropono para sa voice input",
  },
  ar: {
    pageTitle: "استبيان ما قبل الاستشارة",
    chiefComplaint: "الشكوى الرئيسية",
    pastMedicalHistory: "التاريخ المرضي",
    surgicalHistory: "التاريخ الجراحي",
    currentMedications: "الأدوية الحالية",
    otherInfo: "معلومات أخرى (حساسية، إلخ)",
    chiefComplaintPlaceholder: "يرجى وصف سبب زيارتك اليوم",
    pastMedicalHistoryPlaceholder: "يرجى ذكر الأمراض أو الحالات السابقة",
    surgicalHistoryPlaceholder: "يرجى ذكر العمليات الجراحية السابقة",
    currentMedicationsPlaceholder: "يرجى ذكر الأدوية التي تتناولها حالياً",
    otherInfoPlaceholder: "يرجى ذكر الحساسية أو الحالات الخاصة",
    nextButton: "التالي",
    voiceInputHint: "اضغط على زر الميكروفون للإدخال الصوتي",
  },
  uz: {
    pageTitle: "Dastlabki soʻrovnoma",
    chiefComplaint: "Asosiy shikoyat",
    pastMedicalHistory: "Kasallik tarixi",
    surgicalHistory: "Jarrohlik tarixi",
    currentMedications: "Hozirda qabul qilayotgan dorilar",
    otherInfo: "Boshqa maʼlumotlar (allergiya va h.k.)",
    chiefComplaintPlaceholder: "Bugungi tashrifingiz sababini tasvirlang",
    pastMedicalHistoryPlaceholder: "Oldingi kasalliklaringizni sanab oʻting",
    surgicalHistoryPlaceholder: "Oldingi jarrohlik amaliyotlaringizni sanab oʻting",
    currentMedicationsPlaceholder: "Hozirda qabul qilayotgan dorilaringizni sanab oʻting",
    otherInfoPlaceholder: "Allergiya, maxsus holatlar va h.k. haqida yozing",
    nextButton: "Keyingi",
    voiceInputHint: "Matn orqali kiriting (ovozli kiritish mavjud emas)",
  },
  kk: {
    pageTitle: "Алдын ала сауалнама",
    chiefComplaint: "Негізгі шағым",
    pastMedicalHistory: "Ауру тарихы",
    surgicalHistory: "Хирургиялық тарих",
    currentMedications: "Қазір қабылдап жатқан дәрілер",
    otherInfo: "Басқа ақпарат (аллергия, т.б.)",
    chiefComplaintPlaceholder: "Бүгінгі келу себебіңізді сипаттаңыз",
    pastMedicalHistoryPlaceholder: "Бұрынғы ауруларыңызды жазыңыз",
    surgicalHistoryPlaceholder: "Бұрынғы операцияларыңызды жазыңыз",
    currentMedicationsPlaceholder: "Қазір қабылдап жатқан дәрілеріңізді жазыңыз",
    otherInfoPlaceholder: "Аллергия, ерекше жағдайларды жазыңыз",
    nextButton: "Келесі",
    voiceInputHint: "Мәтін арқылы енгізіңіз (дауыстық енгізу қол жетімді емес)",
  },
  id: {
    pageTitle: "Kuesioner Pra-Konsultasi",
    chiefComplaint: "Keluhan Utama",
    pastMedicalHistory: "Riwayat Penyakit",
    surgicalHistory: "Riwayat Operasi",
    currentMedications: "Obat yang Sedang Dikonsumsi",
    otherInfo: "Informasi Lainnya (Alergi, dll.)",
    chiefComplaintPlaceholder: "Jelaskan alasan kunjungan Anda hari ini",
    pastMedicalHistoryPlaceholder: "Sebutkan penyakit atau kondisi yang pernah dialami",
    surgicalHistoryPlaceholder: "Sebutkan operasi yang pernah dilakukan",
    currentMedicationsPlaceholder: "Sebutkan obat yang sedang dikonsumsi",
    otherInfoPlaceholder: "Tuliskan alergi, kondisi khusus, dll.",
    nextButton: "Selanjutnya",
    voiceInputHint: "Tekan tombol mikrofon untuk input suara",
  },
  hi: {
    pageTitle: "पूर्व-परामर्श प्रश्नावली",
    chiefComplaint: "मुख्य शिकायत",
    pastMedicalHistory: "पिछला चिकित्सा इतिहास",
    surgicalHistory: "सर्जरी का इतिहास",
    currentMedications: "वर्तमान में ली जा रही दवाइयाँ",
    otherInfo: "अन्य जानकारी (एलर्जी, आदि)",
    chiefComplaintPlaceholder: "आज की अपनी यात्रा का कारण बताएं",
    pastMedicalHistoryPlaceholder: "पिछली बीमारियों या स्थितियों की सूची दें",
    surgicalHistoryPlaceholder: "पिछली सर्जरी की सूची दें",
    currentMedicationsPlaceholder: "वर्तमान में ली जा रही दवाइयों की सूची दें",
    otherInfoPlaceholder: "एलर्जी, विशेष स्थिति आदि लिखें",
    nextButton: "अगला",
    voiceInputHint: "वॉयस इनपुट के लिए माइक्रोफ़ोन बटन दबाएं",
  },
  de: {
    pageTitle: "Vorab-Fragebogen",
    chiefComplaint: "Hauptbeschwerde",
    pastMedicalHistory: "Krankengeschichte",
    surgicalHistory: "Operationsgeschichte",
    currentMedications: "Aktuelle Medikamente",
    otherInfo: "Weitere Informationen (Allergien usw.)",
    chiefComplaintPlaceholder: "Beschreiben Sie den Grund Ihres heutigen Besuchs",
    pastMedicalHistoryPlaceholder: "Listen Sie frühere Krankheiten oder Zustände auf",
    surgicalHistoryPlaceholder: "Listen Sie frühere Operationen auf",
    currentMedicationsPlaceholder: "Listen Sie Medikamente auf, die Sie derzeit einnehmen",
    otherInfoPlaceholder: "Geben Sie Allergien, besondere Umstände usw. an",
    nextButton: "Weiter",
    voiceInputHint: "Tippen Sie auf die Mikrofontaste für Spracheingabe",
  },
  fr: {
    pageTitle: "Questionnaire de pré-consultation",
    chiefComplaint: "Motif principal de consultation",
    pastMedicalHistory: "Antécédents médicaux",
    surgicalHistory: "Antécédents chirurgicaux",
    currentMedications: "Médicaments actuels",
    otherInfo: "Autres informations (allergies, etc.)",
    chiefComplaintPlaceholder: "Décrivez la raison de votre visite aujourd'hui",
    pastMedicalHistoryPlaceholder: "Listez vos maladies ou conditions passées",
    surgicalHistoryPlaceholder: "Listez vos interventions chirurgicales passées",
    currentMedicationsPlaceholder: "Listez les médicaments que vous prenez actuellement",
    otherInfoPlaceholder: "Indiquez les allergies, conditions spéciales, etc.",
    nextButton: "Suivant",
    voiceInputHint: "Appuyez sur le bouton du microphone pour la saisie vocale",
  },
};
